{
 "title": "IstioService Dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "service",
    "label": "Service",
    "query": "label_values(destination_service)"
   },
   { "name": "qrep", "label": "Reporter", "query": "label_values(reporter)" },
   {
    "name": "srcns",
    "label": "ClientWorkload Namespace",
    "query": "query_result(sum(istio_requests_total{reporter=\"$qrep\",destination_service=\"$service\"}) by (source_workload_namespace) or sum(istio_tcp_sent_bytes_total{reporter=\"$qrep\",destination_service=~\"$service\"}) by (source_workload_namespace))"
   },
   {
    "name": "srcwl",
    "label": "ClientWorkload",
    "query": "query_result(sum(istio_requests_total{reporter=\"$qrep\",destination_service=~\"$service\", source_workload_namespace=~\"$srcns\"})by (source_workload) or sum(istio_tcp_sent_bytes_total{reporter=\"$qrep\",destination_service=~\"$service\", source_workload_namespace=~\"$srcns\"})by (source_workload))"
   },
   {
    "name": "dstns",
    "label": "ServiceWorkload Namespace",
    "query": "query_result(sum(istio_requests_total{reporter=\"destination\",destination_service=\"$service\"}) by (destination_workload_namespace) orsum(istio_tcp_sent_bytes_total{reporter=\"destination\", destination_service=~\"$service\"})by (destination_workload_namespace))"
   },
   {
    "name": "dstwl",
    "label": "ServiceWorkload",
    "query": "query_result(sum(istio_requests_total{reporter=\"destination\", destination_service=~\"$service\",destination_workload_namespace=~\"$dstns\"}) by (destination_workload) orsum(istio_tcp_sent_bytes_total{reporter=\"destination\", destination_service=~\"$service\",destination_workload_namespace=~\"$dstns\"}) by (destination_workload))"
   }
  ]
 },
 "panels": [
  {
   "title": "General",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "type": "text",
     "gridPos": { "h": 3, "w": 24, "x": 0, "y": 1 },
     "options": {
      "content": "<divclass=\"dashboard-header text-center\">\n<span>SERVICE: $service</span>\n</div>"
     },
     "content": "<divclass=\"dashboard-header text-center\">\n<span>SERVICE: $service</span>\n</div>"
    },
    {
     "title": "ClientRequest Volume",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 6, "x": 0, "y": 4 },
     "format": "ops",
     "valueName": "current",
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "round(sum(irate(istio_requests_total{reporter=\"$qrep\",destination_service=~\"$service\"}[5m])),0.001)"
      }
     ]
    },
    {
     "title": "Client Success Rate (non-5xx responses)",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 6, "x": 6, "y": 4 },
     "format": "percentunit",
     "valueName": "avg",
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(irate(istio_requests_total{reporter=\"$qrep\",destination_service=~\"$service\",response_code!~\"5.*\"}[5m]))/ sum(irate(istio_requests_total{reporter=\"$qrep\",destination_service=~\"$service\"}[5m]))"
      }
     ]
    },
    {
     "title": "ClientRequest Duration",
     "type": "graph",
     "gridPos": { "h": 4, "w": 6, "x": 12, "y": 4 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "(histogram_quantile(0.50,sum(irate(istio_request_duration_milliseconds_bucket{reporter=\"$qrep\",destination_service=~\"$service\"}[1m]))by (le)) / 1000) or histogram_quantile(0.50, sum(irate(istio_request_duration_seconds_bucket{reporter=\"$qrep\",destination_service=~\"$service\"}[1m]))by (le))",
       "legendFormat": "P50"
      },
      {
       "expr": "(histogram_quantile(0.90,sum(irate(istio_request_duration_milliseconds_bucket{reporter=\"$qrep\",destination_service=~\"$service\"}[1m]))by (le)) / 1000) or histogram_quantile(0.90, sum(irate(istio_request_duration_seconds_bucket{reporter=\"$qrep\",destination_service=~\"$service\"}[1m]))by (le))",
       "legendFormat": "P90"
      },
      {
       "expr": "(histogram_quantile(0.99,sum(irate(istio_request_duration_milliseconds_bucket{reporter=\"$qrep\",destination_service=~\"$service\"}[1m]))by (le)) / 1000) or histogram_quantile(0.99, sum(irate(istio_request_duration_seconds_bucket{reporter=\"$qrep\",destination_service=~\"$service\"}[1m]))by (le))",
       "legendFormat": "P99"
      }
     ]
    },
    {
     "title": "TCPReceived Bytes",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 6, "x": 18, "y": 4 },
     "format": "Bps",
     "valueName": "avg",
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(irate(istio_tcp_received_bytes_total{reporter=\"$qrep\",destination_service=~\"$service\"}[1m]))"
      }
     ]
    },
    {
     "title": "ServerRequest Volume",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 6, "x": 0, "y": 8 },
     "format": "ops",
     "valueName": "current",
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "round(sum(irate(istio_requests_total{reporter=\"destination\",destination_service=~\"$service\"}[5m])),0.001)"
      }
     ]
    },
    {
     "title": "Server Success Rate (non-5xx responses)",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 6, "x": 6, "y": 8 },
     "format": "percentunit",
     "valueName": "avg",
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(irate(istio_requests_total{reporter=\"destination\",destination_service=~\"$service\",response_code!~\"5.*\"}[5m]))/ sum(irate(istio_requests_total{reporter=\"destination\",destination_service=~\"$service\"}[5m]))"
      }
     ]
    },
    {
     "title": "ServerRequest Duration",
     "type": "graph",
     "gridPos": { "h": 4, "w": 6, "x": 12, "y": 8 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "(histogram_quantile(0.50,sum(irate(istio_request_duration_milliseconds_bucket{reporter=\"destination\",destination_service=~\"$service\"}[1m]))by (le)) / 1000) or histogram_quantile(0.50, sum(irate(istio_request_duration_seconds_bucket{reporter=\"destination\",destination_service=~\"$service\"}[1m]))by (le))",
       "legendFormat": "P50"
      },
      {
       "expr": "(histogram_quantile(0.90,sum(irate(istio_request_duration_milliseconds_bucket{reporter=\"destination\",destination_service=~\"$service\"}[1m]))by (le)) / 1000) or histogram_quantile(0.90, sum(irate(istio_request_duration_seconds_bucket{reporter=\"destination\",destination_service=~\"$service\"}[1m]))by (le))",
       "legendFormat": "P90"
      },
      {
       "expr": "(histogram_quantile(0.99,sum(irate(istio_request_duration_milliseconds_bucket{reporter=\"destination\",destination_service=~\"$service\"}[1m]))by (le)) / 1000) or histogram_quantile(0.99, sum(irate(istio_request_duration_seconds_bucket{reporter=\"destination\",destination_service=~\"$service\"}[1m]))by (le))",
       "legendFormat": "P99"
      }
     ]
    },
    {
     "title": "TCPSent Bytes",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 6, "x": 18, "y": 8 },
     "format": "Bps",
     "valueName": "avg",
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(irate(istio_tcp_sent_bytes_total{reporter=\"$qrep\",destination_service=~\"$service\"}[1m]))"
      }
     ]
    }
   ]
  },
  {
   "title": "ClientWorkloads",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "type": "text",
     "gridPos": { "h": 3, "w": 24, "x": 0, "y": 2 },
     "options": {
      "content": "<divclass=\"dashboard-header text-center\">\n<span>CLIENT WORKLOADS</span>\n</div>"
     },
     "content": "<divclass=\"dashboard-header text-center\">\n<span>CLIENT WORKLOADS</span>\n</div>"
    },
    {
     "title": "IncomingRequests By Source And Response Code",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 5 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "round(sum(irate(istio_requests_total{connection_security_policy=\"mutual_tls\",destination_service=~\"$service\",reporter=\"$qrep\",source_workload=~\"$srcwl\",source_workload_namespace=~\"$srcns\"}[5m]))by (source_workload, source_workload_namespace, response_code), 0.001)",
       "legendFormat": "{{source_workload }}.{{ source_workload_namespace }} : {{ response_code }} (U0001F510mTLS)"
      },
      {
       "expr": "round(sum(irate(istio_requests_total{connection_security_policy!=\"mutual_tls\",destination_service=~\"$service\", reporter=\"$qrep\", source_workload=~\"$srcwl\",source_workload_namespace=~\"$srcns\"}[5m])) by (source_workload, source_workload_namespace,response_code), 0.001)",
       "legendFormat": "{{source_workload }}.{{ source_workload_namespace }} : {{ response_code }}"
      }
     ]
    },
    {
     "title": "IncomingSuccess Rate (non-5xx responses) By Source",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 5 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "sum(irate(istio_requests_total{reporter=\"$qrep\",connection_security_policy=\"mutual_tls\", destination_service=~\"$service\",response_code!~\"5.*\",source_workload=~\"$srcwl\", source_workload_namespace=~\"$srcns\"}[5m]))by (source_workload, source_workload_namespace) / sum(irate(istio_requests_total{reporter=\"$qrep\",connection_security_policy=\"mutual_tls\", destination_service=~\"$service\",source_workload=~\"$srcwl\", source_workload_namespace=~\"$srcns\"}[5m]))by (source_workload, source_workload_namespace)",
       "legendFormat": "{{source_workload }}.{{ source_workload_namespace }} (U0001F510mTLS)"
      },
      {
       "expr": "sum(irate(istio_requests_total{reporter=\"$qrep\",connection_security_policy!=\"mutual_tls\", destination_service=~\"$service\",response_code!~\"5.*\",source_workload=~\"$srcwl\", source_workload_namespace=~\"$srcns\"}[5m]))by (source_workload, source_workload_namespace) / sum(irate(istio_requests_total{reporter=\"$qrep\",connection_security_policy!=\"mutual_tls\", destination_service=~\"$service\",source_workload=~\"$srcwl\", source_workload_namespace=~\"$srcns\"}[5m]))by (source_workload, source_workload_namespace)",
       "legendFormat": "{{source_workload }}.{{ source_workload_namespace }}"
      }
     ]
    },
    {
     "title": "IncomingRequest Duration By Source",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 11 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "(histogram_quantile(0.50,sum(irate(istio_request_duration_milliseconds_bucket{reporter=\"$qrep\", connection_security_policy=\"mutual_tls\",destination_service=~\"$service\", source_workload=~\"$srcwl\", source_workload_namespace=~\"$srcns\"}[1m]))by (source_workload, source_workload_namespace, le)) / 1000) or histogram_quantile(0.50,sum(irate(istio_request_duration_seconds_bucket{reporter=\"$qrep\", connection_security_policy=\"mutual_tls\",destination_service=~\"$service\", source_workload=~\"$srcwl\", source_workload_namespace=~\"$srcns\"}[1m]))by (source_workload, source_workload_namespace, le))",
       "legendFormat": "{{source_workload}}.{{source_workload_namespace}}P50 (U0001F510mTLS)"
      },
      {
       "expr": "(histogram_quantile(0.90,sum(irate(istio_request_duration_milliseconds_bucket{reporter=\"$qrep\", connection_security_policy=\"mutual_tls\",destination_service=~\"$service\", source_workload=~\"$srcwl\", source_workload_namespace=~\"$srcns\"}[1m]))by (source_workload, source_workload_namespace, le)) / 1000) or histogram_quantile(0.90,sum(irate(istio_request_duration_seconds_bucket{reporter=\"$qrep\", connection_security_policy=\"mutual_tls\",destination_service=~\"$service\", source_workload=~\"$srcwl\", source_workload_namespace=~\"$srcns\"}[1m]))by (source_workload, source_workload_namespace, le))",
       "legendFormat": "{{source_workload}}.{{source_workload_namespace}}P90 (U0001F510mTLS)"
      },
      {
       "expr": "(histogram_quantile(0.95,sum(irate(istio_request_duration_milliseconds_bucket{reporter=\"$qrep\", connection_security_policy=\"mutual_tls\",destination_service=~\"$service\", source_workload=~\"$srcwl\", source_workload_namespace=~\"$srcns\"}[1m]))by (source_workload, source_workload_namespace, le)) / 1000) or histogram_quantile(0.95,sum(irate(istio_request_duration_seconds_bucket{reporter=\"$qrep\", connection_security_policy=\"mutual_tls\",destination_service=~\"$service\", source_workload=~\"$srcwl\", source_workload_namespace=~\"$srcns\"}[1m]))by (source_workload, source_workload_namespace, le))",
       "legendFormat": "{{source_workload}}.{{source_workload_namespace}}P95 (U0001F510mTLS)"
      },
      {
       "expr": "(histogram_quantile(0.99,sum(irate(istio_request_duration_milliseconds_bucket{reporter=\"$qrep\", connection_security_policy=\"mutual_tls\",destination_service=~\"$service\", source_workload=~\"$srcwl\", source_workload_namespace=~\"$srcns\"}[1m]))by (source_workload, source_workload_namespace, le)) / 1000) or histogram_quantile(0.99,sum(irate(istio_request_duration_seconds_bucket{reporter=\"$qrep\", connection_security_policy=\"mutual_tls\",destination_service=~\"$service\", source_workload=~\"$srcwl\", source_workload_namespace=~\"$srcns\"}[1m]))by (source_workload, source_workload_namespace, le))",
       "legendFormat": "{{source_workload}}.{{source_workload_namespace}}P99 (U0001F510mTLS)"
      },
      {
       "expr": "(histogram_quantile(0.50,sum(irate(istio_request_duration_milliseconds_bucket{reporter=\"$qrep\", connection_security_policy!=\"mutual_tls\",destination_service=~\"$service\", source_workload=~\"$srcwl\", source_workload_namespace=~\"$srcns\"}[1m]))by (source_workload, source_workload_namespace, le)) / 1000) or histogram_quantile(0.50,sum(irate(istio_request_duration_seconds_bucket{reporter=\"$qrep\", connection_security_policy!=\"mutual_tls\",destination_service=~\"$service\", source_workload=~\"$srcwl\", source_workload_namespace=~\"$srcns\"}[1m]))by (source_workload, source_workload_namespace, le))",
       "legendFormat": "{{source_workload}}.{{source_workload_namespace}}P50"
      },
      {
       "expr": "(histogram_quantile(0.90, sum(irate(istio_request_duration_milliseconds_bucket{reporter=\"$qrep\",connection_security_policy!=\"mutual_tls\", destination_service=~\"$service\",source_workload=~\"$srcwl\", source_workload_namespace=~\"$srcns\"}[1m]))by (source_workload, source_workload_namespace, le)) / 1000) or histogram_quantile(0.90,sum(irate(istio_request_duration_seconds_bucket{reporter=\"$qrep\", connection_security_policy!=\"mutual_tls\",destination_service=~\"$service\", source_workload=~\"$srcwl\", source_workload_namespace=~\"$srcns\"}[1m]))by (source_workload, source_workload_namespace, le))",
       "legendFormat": "{{source_workload}}.{{source_workload_namespace}}P90"
      },
      {
       "expr": "(histogram_quantile(0.95, sum(irate(istio_request_duration_milliseconds_bucket{reporter=\"$qrep\",connection_security_policy!=\"mutual_tls\", destination_service=~\"$service\",source_workload=~\"$srcwl\", source_workload_namespace=~\"$srcns\"}[1m]))by (source_workload, source_workload_namespace, le)) / 1000) or histogram_quantile(0.95,sum(irate(istio_request_duration_seconds_bucket{reporter=\"$qrep\", connection_security_policy!=\"mutual_tls\",destination_service=~\"$service\", source_workload=~\"$srcwl\", source_workload_namespace=~\"$srcns\"}[1m]))by (source_workload, source_workload_namespace, le))",
       "legendFormat": "{{source_workload}}.{{source_workload_namespace}}P95"
      },
      {
       "expr": "(histogram_quantile(0.99, sum(irate(istio_request_duration_milliseconds_bucket{reporter=\"$qrep\",connection_security_policy!=\"mutual_tls\", destination_service=~\"$service\",source_workload=~\"$srcwl\", source_workload_namespace=~\"$srcns\"}[1m]))by (source_workload, source_workload_namespace, le)) / 1000) or histogram_quantile(0.99,sum(irate(istio_request_duration_seconds_bucket{reporter=\"$qrep\", connection_security_policy!=\"mutual_tls\",destination_service=~\"$service\", source_workload=~\"$srcwl\", source_workload_namespace=~\"$srcns\"}[1m]))by (source_workload, source_workload_namespace, le))",
       "legendFormat": "{{source_workload}}.{{source_workload_namespace}}P99"
      }
     ]
    },
    {
     "title": "IncomingRequest Size By Source",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 11 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.50,sum(irate(istio_request_bytes_bucket{reporter=\"$qrep\", connection_security_policy=\"mutual_tls\",destination_service=~\"$service\", source_workload=~\"$srcwl\", source_workload_namespace=~\"$srcns\"}[1m]))by (source_workload, source_workload_namespace, le))",
       "legendFormat": "{{source_workload}}.{{source_workload_namespace}}P50 (U0001F510mTLS)"
      },
      {
       "expr": "histogram_quantile(0.90,sum(irate(istio_request_bytes_bucket{reporter=\"$qrep\", connection_security_policy=\"mutual_tls\",destination_service=~\"$service\", source_workload=~\"$srcwl\", source_workload_namespace=~\"$srcns\"}[1m]))by (source_workload, source_workload_namespace, le))",
       "legendFormat": "{{source_workload}}.{{source_workload_namespace}} P90 (U0001F510mTLS)"
      },
      {
       "expr": "histogram_quantile(0.95,sum(irate(istio_request_bytes_bucket{reporter=\"$qrep\", connection_security_policy=\"mutual_tls\",destination_service=~\"$service\", source_workload=~\"$srcwl\", source_workload_namespace=~\"$srcns\"}[1m]))by (source_workload, source_workload_namespace, le))",
       "legendFormat": "{{source_workload}}.{{source_workload_namespace}}P95 (U0001F510mTLS)"
      },
      {
       "expr": "histogram_quantile(0.99,sum(irate(istio_request_bytes_bucket{reporter=\"$qrep\", connection_security_policy=\"mutual_tls\",destination_service=~\"$service\", source_workload=~\"$srcwl\", source_workload_namespace=~\"$srcns\"}[1m]))by (source_workload, source_workload_namespace, le))",
       "legendFormat": "{{source_workload}}.{{source_workload_namespace}} P99 (U0001F510mTLS)"
      },
      {
       "expr": "histogram_quantile(0.50,sum(irate(istio_request_bytes_bucket{reporter=\"$qrep\", connection_security_policy!=\"mutual_tls\",destination_service=~\"$service\", source_workload=~\"$srcwl\", source_workload_namespace=~\"$srcns\"}[1m]))by (source_workload, source_workload_namespace, le))",
       "legendFormat": "{{source_workload}}.{{source_workload_namespace}}P50"
      },
      {
       "expr": "histogram_quantile(0.90, sum(irate(istio_request_bytes_bucket{reporter=\"$qrep\",connection_security_policy!=\"mutual_tls\", destination_service=~\"$service\",source_workload=~\"$srcwl\", source_workload_namespace=~\"$srcns\"}[1m]))by (source_workload, source_workload_namespace, le))",
       "legendFormat": "{{source_workload}}.{{source_workload_namespace}}P90"
      },
      {
       "expr": "histogram_quantile(0.95, sum(irate(istio_request_bytes_bucket{reporter=\"$qrep\",connection_security_policy!=\"mutual_tls\", destination_service=~\"$service\",source_workload=~\"$srcwl\", source_workload_namespace=~\"$srcns\"}[1m]))by (source_workload, source_workload_namespace, le))",
       "legendFormat": "{{source_workload}}.{{source_workload_namespace}}P95"
      },
      {
       "expr": "histogram_quantile(0.99, sum(irate(istio_request_bytes_bucket{reporter=\"$qrep\",connection_security_policy!=\"mutual_tls\", destination_service=~\"$service\",source_workload=~\"$srcwl\", source_workload_namespace=~\"$srcns\"}[1m]))by (source_workload, source_workload_namespace, le))",
       "legendFormat": "{{source_workload}}.{{source_workload_namespace}}P99"
      }
     ]
    },
    {
     "title": "ResponseSize By Source",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 11 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.50,sum(irate(istio_response_bytes_bucket{reporter=\"$qrep\", connection_security_policy=\"mutual_tls\",destination_service=~\"$service\", source_workload=~\"$srcwl\", source_workload_namespace=~\"$srcns\"}[1m]))by (source_workload, source_workload_namespace, le))",
       "legendFormat": "{{source_workload}}.{{source_workload_namespace}}P50 (U0001F510mTLS)"
      },
      {
       "expr": "histogram_quantile(0.90,sum(irate(istio_response_bytes_bucket{reporter=\"$qrep\", connection_security_policy=\"mutual_tls\",destination_service=~\"$service\", source_workload=~\"$srcwl\", source_workload_namespace=~\"$srcns\"}[1m]))by (source_workload, source_workload_namespace, le))",
       "legendFormat": "{{source_workload}}.{{source_workload_namespace}} P90 (U0001F510mTLS)"
      },
      {
       "expr": "histogram_quantile(0.95,sum(irate(istio_response_bytes_bucket{reporter=\"$qrep\", connection_security_policy=\"mutual_tls\",destination_service=~\"$service\", source_workload=~\"$srcwl\", source_workload_namespace=~\"$srcns\"}[1m]))by (source_workload, source_workload_namespace, le))",
       "legendFormat": "{{source_workload}}.{{source_workload_namespace}}P95 (U0001F510mTLS)"
      },
      {
       "expr": "histogram_quantile(0.99,sum(irate(istio_response_bytes_bucket{reporter=\"$qrep\", connection_security_policy=\"mutual_tls\",destination_service=~\"$service\", source_workload=~\"$srcwl\", source_workload_namespace=~\"$srcns\"}[1m]))by (source_workload, source_workload_namespace, le))",
       "legendFormat": "{{source_workload}}.{{source_workload_namespace}} P99 (U0001F510mTLS)"
      },
      {
       "expr": "histogram_quantile(0.50,sum(irate(istio_response_bytes_bucket{reporter=\"$qrep\", connection_security_policy!=\"mutual_tls\",destination_service=~\"$service\", source_workload=~\"$srcwl\", source_workload_namespace=~\"$srcns\"}[1m]))by (source_workload, source_workload_namespace, le))",
       "legendFormat": "{{source_workload}}.{{source_workload_namespace}}P50"
      },
      {
       "expr": "histogram_quantile(0.90, sum(irate(istio_response_bytes_bucket{reporter=\"$qrep\",connection_security_policy!=\"mutual_tls\", destination_service=~\"$service\",source_workload=~\"$srcwl\", source_workload_namespace=~\"$srcns\"}[1m]))by (source_workload, source_workload_namespace, le))",
       "legendFormat": "{{source_workload}}.{{source_workload_namespace}}P90"
      },
      {
       "expr": "histogram_quantile(0.95, sum(irate(istio_response_bytes_bucket{reporter=\"$qrep\",connection_security_policy!=\"mutual_tls\", destination_service=~\"$service\",source_workload=~\"$srcwl\", source_workload_namespace=~\"$srcns\"}[1m]))by (source_workload, source_workload_namespace, le))",
       "legendFormat": "{{source_workload}}.{{source_workload_namespace}}P95"
      },
      {
       "expr": "histogram_quantile(0.99, sum(irate(istio_response_bytes_bucket{reporter=\"$qrep\",connection_security_policy!=\"mutual_tls\", destination_service=~\"$service\",source_workload=~\"$srcwl\", source_workload_namespace=~\"$srcns\"}[1m]))by (source_workload, source_workload_namespace, le))",
       "legendFormat": "{{source_workload}}.{{source_workload_namespace}}P99"
      }
     ]
    },
    {
     "title": "BytesReceived from Incoming TCP Connection",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 17 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "round(sum(irate(istio_tcp_received_bytes_total{reporter=\"$qrep\",connection_security_policy=\"mutual_tls\", destination_service=~\"$service\",source_workload=~\"$srcwl\", source_workload_namespace=~\"$srcns\"}[1m]))by (source_workload, source_workload_namespace), 0.001)",
       "legendFormat": "{{source_workload }}.{{ source_workload_namespace}} (U0001F510mTLS)"
      },
      {
       "expr": "round(sum(irate(istio_tcp_received_bytes_total{reporter=\"$qrep\",connection_security_policy!=\"mutual_tls\", destination_service=~\"$service\",source_workload=~\"$srcwl\", source_workload_namespace=~\"$srcns\"}[1m]))by (source_workload, source_workload_namespace), 0.001)",
       "legendFormat": "{{source_workload }}.{{ source_workload_namespace}}"
      }
     ]
    },
    {
     "title": "BytesSent to Incoming TCP Connection",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 17 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "round(sum(irate(istio_tcp_sent_bytes_total{connection_security_policy=\"mutual_tls\",reporter=\"$qrep\", destination_service=~\"$service\", source_workload=~\"$srcwl\",source_workload_namespace=~\"$srcns\"}[1m])) by (source_workload, source_workload_namespace),0.001)",
       "legendFormat": "{{source_workload }}.{{ source_workload_namespace}} (U0001F510mTLS)"
      },
      {
       "expr": "round(sum(irate(istio_tcp_sent_bytes_total{connection_security_policy!=\"mutual_tls\",reporter=\"$qrep\", destination_service=~\"$service\", source_workload=~\"$srcwl\",source_workload_namespace=~\"$srcns\"}[1m])) by (source_workload, source_workload_namespace),0.001)",
       "legendFormat": "{{source_workload }}.{{ source_workload_namespace}}"
      }
     ]
    }
   ]
  },
  {
   "title": "ServiceWorkloads",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "type": "text",
     "gridPos": { "h": 3, "w": 24, "x": 0, "y": 3 },
     "options": {
      "content": "<divclass=\"dashboard-header text-center\">\n<span>SERVICE WORKLOADS</span>\n</div>"
     },
     "content": "<divclass=\"dashboard-header text-center\">\n<span>SERVICE WORKLOADS</span>\n</div>"
    },
    {
     "title": "IncomingRequests By Destination Workload And Response Code",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 6 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "round(sum(irate(istio_requests_total{connection_security_policy=\"mutual_tls\",destination_service=~\"$service\",reporter=\"destination\",destination_workload=~\"$dstwl\",destination_workload_namespace=~\"$dstns\"}[5m]))by (destination_workload, destination_workload_namespace, response_code), 0.001)",
       "legendFormat": "{{destination_workload }}.{{ destination_workload_namespace }} : {{ response_code}} (U0001F510mTLS)"
      },
      {
       "expr": "round(sum(irate(istio_requests_total{connection_security_policy!=\"mutual_tls\",destination_service=~\"$service\", reporter=\"destination\", destination_workload=~\"$dstwl\",destination_workload_namespace=~\"$dstns\"}[5m])) by (destination_workload,destination_workload_namespace, response_code), 0.001)",
       "legendFormat": "{{destination_workload }}.{{ destination_workload_namespace }} : {{ response_code}}"
      }
     ]
    },
    {
     "title": "IncomingSuccess Rate (non-5xx responses) By Destination Workload",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 6 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "sum(irate(istio_requests_total{reporter=\"destination\",connection_security_policy=\"mutual_tls\", destination_service=~\"$service\",response_code!~\"5.*\",destination_workload=~\"$dstwl\", destination_workload_namespace=~\"$dstns\"}[5m]))by (destination_workload, destination_workload_namespace) / sum(irate(istio_requests_total{reporter=\"destination\",connection_security_policy=\"mutual_tls\", destination_service=~\"$service\",destination_workload=~\"$dstwl\", destination_workload_namespace=~\"$dstns\"}[5m]))by (destination_workload, destination_workload_namespace)",
       "legendFormat": "{{destination_workload }}.{{ destination_workload_namespace }} (U0001F510mTLS)"
      },
      {
       "expr": "sum(irate(istio_requests_total{reporter=\"destination\",connection_security_policy!=\"mutual_tls\", destination_service=~\"$service\",response_code!~\"5.*\",destination_workload=~\"$dstwl\", destination_workload_namespace=~\"$dstns\"}[5m]))by (destination_workload, destination_workload_namespace) / sum(irate(istio_requests_total{reporter=\"destination\",connection_security_policy!=\"mutual_tls\", destination_service=~\"$service\",destination_workload=~\"$dstwl\", destination_workload_namespace=~\"$dstns\"}[5m]))by (destination_workload, destination_workload_namespace)",
       "legendFormat": "{{destination_workload }}.{{ destination_workload_namespace }}"
      }
     ]
    },
    {
     "title": "IncomingRequest Duration By Service Workload",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 12 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "(histogram_quantile(0.50,sum(irate(istio_request_duration_milliseconds_bucket{reporter=\"destination\",connection_security_policy=\"mutual_tls\", destination_service=~\"$service\",destination_workload=~\"$dstwl\", destination_workload_namespace=~\"$dstns\"}[1m]))by (destination_workload, destination_workload_namespace, le)) / 1000) or histogram_quantile(0.50,sum(irate(istio_request_duration_seconds_bucket{reporter=\"destination\",connection_security_policy=\"mutual_tls\", destination_service=~\"$service\",destination_workload=~\"$dstwl\", destination_workload_namespace=~\"$dstns\"}[1m]))by (destination_workload, destination_workload_namespace, le))",
       "legendFormat": "{{destination_workload }}.{{ destination_workload_namespace }} P50 (U0001F510mTLS)"
      },
      {
       "expr": "(histogram_quantile(0.90,sum(irate(istio_request_duration_milliseconds_bucket{reporter=\"destination\",connection_security_policy=\"mutual_tls\", destination_service=~\"$service\",destination_workload=~\"$dstwl\", destination_workload_namespace=~\"$dstns\"}[1m]))by (destination_workload, destination_workload_namespace, le)) / 1000) or histogram_quantile(0.90,sum(irate(istio_request_duration_seconds_bucket{reporter=\"destination\",connection_security_policy=\"mutual_tls\", destination_service=~\"$service\",destination_workload=~\"$dstwl\", destination_workload_namespace=~\"$dstns\"}[1m]))by (destination_workload, destination_workload_namespace, le))",
       "legendFormat": "{{destination_workload }}.{{ destination_workload_namespace }} P90 (U0001F510mTLS)"
      },
      {
       "expr": "(histogram_quantile(0.95,sum(irate(istio_request_duration_milliseconds_bucket{reporter=\"destination\",connection_security_policy=\"mutual_tls\", destination_service=~\"$service\",destination_workload=~\"$dstwl\", destination_workload_namespace=~\"$dstns\"}[1m]))by (destination_workload, destination_workload_namespace, le)) / 1000) or histogram_quantile(0.95,sum(irate(istio_request_duration_seconds_bucket{reporter=\"destination\",connection_security_policy=\"mutual_tls\", destination_service=~\"$service\",destination_workload=~\"$dstwl\", destination_workload_namespace=~\"$dstns\"}[1m]))by (destination_workload, destination_workload_namespace, le))",
       "legendFormat": "{{destination_workload }}.{{ destination_workload_namespace }} P95 (U0001F510mTLS)"
      },
      {
       "expr": "(histogram_quantile(0.99,sum(irate(istio_request_duration_milliseconds_bucket{reporter=\"destination\",connection_security_policy=\"mutual_tls\", destination_service=~\"$service\",destination_workload=~\"$dstwl\", destination_workload_namespace=~\"$dstns\"}[1m]))by (destination_workload, destination_workload_namespace, le)) / 1000) or histogram_quantile(0.99,sum(irate(istio_request_duration_seconds_bucket{reporter=\"destination\",connection_security_policy=\"mutual_tls\", destination_service=~\"$service\",destination_workload=~\"$dstwl\", destination_workload_namespace=~\"$dstns\"}[1m]))by (destination_workload, destination_workload_namespace, le))",
       "legendFormat": "{{destination_workload }}.{{ destination_workload_namespace }} P99 (U0001F510mTLS)"
      },
      {
       "expr": "(histogram_quantile(0.50,sum(irate(istio_request_duration_milliseconds_bucket{reporter=\"destination\",connection_security_policy!=\"mutual_tls\", destination_service=~\"$service\",destination_workload=~\"$dstwl\", destination_workload_namespace=~\"$dstns\"}[1m]))by (destination_workload, destination_workload_namespace, le)) / 1000) or histogram_quantile(0.50,sum(irate(istio_request_duration_seconds_bucket{reporter=\"destination\",connection_security_policy!=\"mutual_tls\", destination_service=~\"$service\",destination_workload=~\"$dstwl\", destination_workload_namespace=~\"$dstns\"}[1m]))by (destination_workload, destination_workload_namespace, le))",
       "legendFormat": "{{destination_workload }}.{{ destination_workload_namespace }} P50"
      },
      {
       "expr": "(histogram_quantile(0.90,sum(irate(istio_request_duration_milliseconds_bucket{reporter=\"destination\",connection_security_policy!=\"mutual_tls\", destination_service=~\"$service\",destination_workload=~\"$dstwl\", destination_workload_namespace=~\"$dstns\"}[1m]))by (destination_workload, destination_workload_namespace, le)) / 1000) or histogram_quantile(0.90,sum(irate(istio_request_duration_seconds_bucket{reporter=\"destination\",connection_security_policy!=\"mutual_tls\", destination_service=~\"$service\",destination_workload=~\"$dstwl\", destination_workload_namespace=~\"$dstns\"}[1m]))by (destination_workload, destination_workload_namespace, le))",
       "legendFormat": "{{destination_workload }}.{{ destination_workload_namespace }} P90"
      },
      {
       "expr": "(histogram_quantile(0.95,sum(irate(istio_request_duration_milliseconds_bucket{reporter=\"destination\",connection_security_policy!=\"mutual_tls\", destination_service=~\"$service\",destination_workload=~\"$dstwl\", destination_workload_namespace=~\"$dstns\"}[1m]))by (destination_workload, destination_workload_namespace, le)) / 1000) or histogram_quantile(0.95,sum(irate(istio_request_duration_seconds_bucket{reporter=\"destination\",connection_security_policy!=\"mutual_tls\", destination_service=~\"$service\",destination_workload=~\"$dstwl\", destination_workload_namespace=~\"$dstns\"}[1m]))by (destination_workload, destination_workload_namespace, le))",
       "legendFormat": "{{destination_workload }}.{{ destination_workload_namespace }} P95"
      },
      {
       "expr": "(histogram_quantile(0.99,sum(irate(istio_request_duration_milliseconds_bucket{reporter=\"destination\",connection_security_policy!=\"mutual_tls\", destination_service=~\"$service\",destination_workload=~\"$dstwl\", destination_workload_namespace=~\"$dstns\"}[1m]))by (destination_workload, destination_workload_namespace, le)) / 1000) or histogram_quantile(0.99,sum(irate(istio_request_duration_seconds_bucket{reporter=\"destination\",connection_security_policy!=\"mutual_tls\", destination_service=~\"$service\",destination_workload=~\"$dstwl\", destination_workload_namespace=~\"$dstns\"}[1m]))by (destination_workload, destination_workload_namespace, le))",
       "legendFormat": "{{destination_workload }}.{{ destination_workload_namespace }} P99"
      }
     ]
    },
    {
     "title": "IncomingRequest Size By Service Workload",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 12 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.50,sum(irate(istio_request_bytes_bucket{reporter=\"destination\", connection_security_policy=\"mutual_tls\",destination_service=~\"$service\", destination_workload=~\"$dstwl\", destination_workload_namespace=~\"$dstns\"}[1m]))by (destination_workload, destination_workload_namespace, le))",
       "legendFormat": "{{destination_workload }}.{{ destination_workload_namespace }} P50 (U0001F510mTLS)"
      },
      {
       "expr": "histogram_quantile(0.90,sum(irate(istio_request_bytes_bucket{reporter=\"destination\", connection_security_policy=\"mutual_tls\",destination_service=~\"$service\", destination_workload=~\"$dstwl\", destination_workload_namespace=~\"$dstns\"}[1m]))by (destination_workload, destination_workload_namespace, le))",
       "legendFormat": "{{destination_workload }}.{{ destination_workload_namespace }}  P90 (U0001F510mTLS)"
      },
      {
       "expr": "histogram_quantile(0.95,sum(irate(istio_request_bytes_bucket{reporter=\"destination\", connection_security_policy=\"mutual_tls\",destination_service=~\"$service\", destination_workload=~\"$dstwl\", destination_workload_namespace=~\"$dstns\"}[1m]))by (destination_workload, destination_workload_namespace, le))",
       "legendFormat": "{{destination_workload }}.{{ destination_workload_namespace }} P95 (U0001F510mTLS)"
      },
      {
       "expr": "histogram_quantile(0.99,sum(irate(istio_request_bytes_bucket{reporter=\"destination\", connection_security_policy=\"mutual_tls\",destination_service=~\"$service\", destination_workload=~\"$dstwl\", destination_workload_namespace=~\"$dstns\"}[1m]))by (destination_workload, destination_workload_namespace, le))",
       "legendFormat": "{{destination_workload }}.{{ destination_workload_namespace }}  P99 (U0001F510mTLS)"
      },
      {
       "expr": "histogram_quantile(0.50,sum(irate(istio_request_bytes_bucket{reporter=\"destination\", connection_security_policy!=\"mutual_tls\",destination_service=~\"$service\", destination_workload=~\"$dstwl\", destination_workload_namespace=~\"$dstns\"}[1m]))by (destination_workload, destination_workload_namespace, le))",
       "legendFormat": "{{destination_workload }}.{{ destination_workload_namespace }} P50"
      },
      {
       "expr": "histogram_quantile(0.90,sum(irate(istio_request_bytes_bucket{reporter=\"destination\", connection_security_policy!=\"mutual_tls\",destination_service=~\"$service\", destination_workload=~\"$dstwl\", destination_workload_namespace=~\"$dstns\"}[1m]))by (destination_workload, destination_workload_namespace, le))",
       "legendFormat": "{{destination_workload }}.{{ destination_workload_namespace }} P90"
      },
      {
       "expr": "histogram_quantile(0.95,sum(irate(istio_request_bytes_bucket{reporter=\"destination\", connection_security_policy!=\"mutual_tls\",destination_service=~\"$service\", destination_workload=~\"$dstwl\", destination_workload_namespace=~\"$dstns\"}[1m]))by (destination_workload, destination_workload_namespace, le))",
       "legendFormat": "{{destination_workload }}.{{ destination_workload_namespace }} P95"
      },
      {
       "expr": "histogram_quantile(0.99,sum(irate(istio_request_bytes_bucket{reporter=\"destination\", connection_security_policy!=\"mutual_tls\",destination_service=~\"$service\", destination_workload=~\"$dstwl\", destination_workload_namespace=~\"$dstns\"}[1m]))by (destination_workload, destination_workload_namespace, le))",
       "legendFormat": "{{destination_workload }}.{{ destination_workload_namespace }} P99"
      }
     ]
    },
    {
     "title": "ResponseSize By Service Workload",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 12 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.50,sum(irate(istio_response_bytes_bucket{reporter=\"destination\", connection_security_policy=\"mutual_tls\",destination_service=~\"$service\", destination_workload=~\"$dstwl\", destination_workload_namespace=~\"$dstns\"}[1m]))by (destination_workload, destination_workload_namespace, le))",
       "legendFormat": "{{destination_workload }}.{{ destination_workload_namespace }} P50 (U0001F510mTLS)"
      },
      {
       "expr": "histogram_quantile(0.90,sum(irate(istio_response_bytes_bucket{reporter=\"destination\", connection_security_policy=\"mutual_tls\",destination_service=~\"$service\", destination_workload=~\"$dstwl\", destination_workload_namespace=~\"$dstns\"}[1m]))by (destination_workload, destination_workload_namespace, le))",
       "legendFormat": "{{destination_workload }}.{{ destination_workload_namespace }}  P90 (U0001F510mTLS)"
      },
      {
       "expr": "histogram_quantile(0.95,sum(irate(istio_response_bytes_bucket{reporter=\"destination\", connection_security_policy=\"mutual_tls\",destination_service=~\"$service\", destination_workload=~\"$dstwl\", destination_workload_namespace=~\"$dstns\"}[1m]))by (destination_workload, destination_workload_namespace, le))",
       "legendFormat": "{{destination_workload }}.{{ destination_workload_namespace }} P95 (U0001F510mTLS)"
      },
      {
       "expr": "histogram_quantile(0.99,sum(irate(istio_response_bytes_bucket{reporter=\"destination\", connection_security_policy=\"mutual_tls\",destination_service=~\"$service\", destination_workload=~\"$dstwl\", destination_workload_namespace=~\"$dstns\"}[1m]))by (destination_workload, destination_workload_namespace, le))",
       "legendFormat": "{{destination_workload }}.{{ destination_workload_namespace }}  P99 (U0001F510mTLS)"
      },
      {
       "expr": "histogram_quantile(0.50,sum(irate(istio_response_bytes_bucket{reporter=\"destination\", connection_security_policy!=\"mutual_tls\",destination_service=~\"$service\", destination_workload=~\"$dstwl\", destination_workload_namespace=~\"$dstns\"}[1m]))by (destination_workload, destination_workload_namespace, le))",
       "legendFormat": "{{destination_workload }}.{{ destination_workload_namespace }} P50"
      },
      {
       "expr": "histogram_quantile(0.90,sum(irate(istio_response_bytes_bucket{reporter=\"destination\", connection_security_policy!=\"mutual_tls\",destination_service=~\"$service\", destination_workload=~\"$dstwl\", destination_workload_namespace=~\"$dstns\"}[1m]))by (destination_workload, destination_workload_namespace, le))",
       "legendFormat": "{{destination_workload }}.{{ destination_workload_namespace }} P90"
      },
      {
       "expr": "histogram_quantile(0.95,sum(irate(istio_response_bytes_bucket{reporter=\"destination\", connection_security_policy!=\"mutual_tls\",destination_service=~\"$service\", destination_workload=~\"$dstwl\", destination_workload_namespace=~\"$dstns\"}[1m]))by (destination_workload, destination_workload_namespace, le))",
       "legendFormat": "{{destination_workload }}.{{ destination_workload_namespace }} P95"
      },
      {
       "expr": "histogram_quantile(0.99,sum(irate(istio_response_bytes_bucket{reporter=\"destination\", connection_security_policy!=\"mutual_tls\",destination_service=~\"$service\", destination_workload=~\"$dstwl\", destination_workload_namespace=~\"$dstns\"}[1m]))by (destination_workload, destination_workload_namespace, le))",
       "legendFormat": "{{destination_workload }}.{{ destination_workload_namespace }} P99"
      }
     ]
    },
    {
     "title": "BytesReceived from Incoming TCP Connection",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 18 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "round(sum(irate(istio_tcp_received_bytes_total{reporter=\"destination\",connection_security_policy=\"mutual_tls\", destination_service=~\"$service\",destination_workload=~\"$dstwl\", destination_workload_namespace=~\"$dstns\"}[1m]))by (destination_workload, destination_workload_namespace), 0.001)",
       "legendFormat": "{{destination_workload }}.{{ destination_workload_namespace}} (U0001F510mTLS)"
      },
      {
       "expr": "round(sum(irate(istio_tcp_received_bytes_total{reporter=\"destination\",connection_security_policy!=\"mutual_tls\", destination_service=~\"$service\",destination_workload=~\"$dstwl\", destination_workload_namespace=~\"$dstns\"}[1m]))by (destination_workload, destination_workload_namespace), 0.001)",
       "legendFormat": "{{destination_workload }}.{{ destination_workload_namespace}}"
      }
     ]
    },
    {
     "title": "BytesSent to Incoming TCP Connection",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 18 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "round(sum(irate(istio_tcp_sent_bytes_total{connection_security_policy=\"mutual_tls\",reporter=\"destination\", destination_service=~\"$service\", destination_workload=~\"$dstwl\",destination_workload_namespace=~\"$dstns\"}[1m])) by (destination_workload,destination_workload_namespace), 0.001)",
       "legendFormat": "{{destination_workload }}.{{destination_workload_namespace }} (U0001F510mTLS)"
      },
      {
       "expr": "round(sum(irate(istio_tcp_sent_bytes_total{connection_security_policy!=\"mutual_tls\",reporter=\"destination\", destination_service=~\"$service\", destination_workload=~\"$dstwl\",destination_workload_namespace=~\"$dstns\"}[1m])) by (destination_workload,destination_workload_namespace), 0.001)",
       "legendFormat": "{{destination_workload }}.{{destination_workload_namespace }}"
      }
     ]
    }
   ]
  }
 ]
}