{
 "title": "IstioWorkload Dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": "query_result(sum(istio_requests_total)by (destination_workload_namespace) or sum(istio_tcp_sent_bytes_total) by (destination_workload_namespace))"
   },
   {
    "name": "workload",
    "label": "Workload",
    "query": "query_result((sum(istio_requests_total{destination_workload_namespace=~\"$namespace\"})by (destination_workload) or sum(istio_requests_total{source_workload_namespace=~\"$namespace\"})by (source_workload)) or (sum(istio_tcp_sent_bytes_total{destination_workload_namespace=~\"$namespace\"})by (destination_workload) or sum(istio_tcp_sent_bytes_total{source_workload_namespace=~\"$namespace\"})by (source_workload)))"
   },
   { "name": "qrep", "label": "Reporter", "query": "label_values(reporter)" },
   {
    "name": "srcns",
    "label": "InboundWorkload Namespace",
    "query": "query_result(sum(istio_requests_total{reporter=\"$qrep\",destination_workload=\"$workload\", destination_workload_namespace=~\"$namespace\"})by (source_workload_namespace) or sum(istio_tcp_sent_bytes_total{reporter=\"$qrep\",destination_workload=\"$workload\", destination_workload_namespace=~\"$namespace\"})by (source_workload_namespace))"
   },
   {
    "name": "srcwl",
    "label": "InboundWorkload",
    "query": "query_result(sum(istio_requests_total{reporter=\"$qrep\",destination_workload=\"$workload\", destination_workload_namespace=~\"$namespace\",source_workload_namespace=~\"$srcns\"}) by (source_workload) or sum(istio_tcp_sent_bytes_total{reporter=\"$qrep\",destination_workload=\"$workload\", destination_workload_namespace=~\"$namespace\",source_workload_namespace=~\"$srcns\"}) by (source_workload))"
   },
   {
    "name": "dstsvc",
    "label": "DestinationService",
    "query": "query_result(sum(istio_requests_total{reporter=\"source\",source_workload=~\"$workload\", source_workload_namespace=~\"$namespace\"})by (destination_service) or sum(istio_tcp_sent_bytes_total{reporter=\"source\",source_workload=~\"$workload\", source_workload_namespace=~\"$namespace\"})by (destination_service))"
   }
  ]
 },
 "panels": [
  {
   "title": "General",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "type": "text",
     "gridPos": { "h": 3, "w": 24, "x": 0, "y": 1 },
     "options": {
      "content": "<divclass=\"dashboard-header text-center\">\n<span>WORKLOAD: $workload.$namespace</span>\n</div>"
     },
     "content": "<divclass=\"dashboard-header text-center\">\n<span>WORKLOAD: $workload.$namespace</span>\n</div>"
    },
    {
     "title": "IncomingRequest Volume",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 8, "x": 0, "y": 4 },
     "format": "ops",
     "valueName": "current",
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "round(sum(irate(istio_requests_total{reporter=\"$qrep\",destination_workload_namespace=~\"$namespace\",destination_workload=~\"$workload\"}[5m])),0.001)"
      }
     ]
    },
    {
     "title": "Incoming Success Rate (non-5xx responses)",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 8, "x": 8, "y": 4 },
     "format": "percentunit",
     "valueName": "avg",
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(irate(istio_requests_total{reporter=\"$qrep\",destination_workload_namespace=~\"$namespace\",destination_workload=~\"$workload\",response_code!~\"5.*\"}[5m]))/ sum(irate(istio_requests_total{reporter=\"$qrep\",destination_workload_namespace=~\"$namespace\",destination_workload=~\"$workload\"}[5m]))"
      }
     ]
    },
    {
     "title": "RequestDuration",
     "type": "graph",
     "gridPos": { "h": 4, "w": 8, "x": 16, "y": 4 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "(histogram_quantile(0.50,sum(irate(istio_request_duration_milliseconds_bucket{reporter=\"$qrep\",destination_workload=~\"$workload\",destination_workload_namespace=~\"$namespace\"}[1m])) by (le)) / 1000) orhistogram_quantile(0.50, sum(irate(istio_request_duration_seconds_bucket{reporter=\"$qrep\",destination_workload=~\"$workload\",destination_workload_namespace=~\"$namespace\"}[1m])) by (le))",
       "legendFormat": "P50"
      },
      {
       "expr": "(histogram_quantile(0.90,sum(irate(istio_request_duration_milliseconds_bucket{reporter=\"$qrep\",destination_workload=~\"$workload\",destination_workload_namespace=~\"$namespace\"}[1m])) by (le)) / 1000) orhistogram_quantile(0.90, sum(irate(istio_request_duration_seconds_bucket{reporter=\"$qrep\",destination_workload=~\"$workload\",destination_workload_namespace=~\"$namespace\"}[1m])) by (le))",
       "legendFormat": "P90"
      },
      {
       "expr": "(histogram_quantile(0.99,sum(irate(istio_request_duration_milliseconds_bucket{reporter=\"$qrep\",destination_workload=~\"$workload\",destination_workload_namespace=~\"$namespace\"}[1m])) by (le)) / 1000) orhistogram_quantile(0.99, sum(irate(istio_request_duration_seconds_bucket{reporter=\"$qrep\",destination_workload=~\"$workload\",destination_workload_namespace=~\"$namespace\"}[1m])) by (le))",
       "legendFormat": "P99"
      }
     ]
    },
    {
     "title": "TCPServer Traffic",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 12, "x": 0, "y": 8 },
     "format": "Bps",
     "valueName": "avg",
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(irate(istio_tcp_sent_bytes_total{reporter=\"$qrep\",destination_workload_namespace=~\"$namespace\", destination_workload=~\"$workload\"}[1m]))+ sum(irate(istio_tcp_received_bytes_total{reporter=\"$qrep\", destination_workload_namespace=~\"$namespace\",destination_workload=~\"$workload\"}[1m]))"
      }
     ]
    },
    {
     "title": "TCPClient Traffic",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 12, "x": 12, "y": 8 },
     "format": "Bps",
     "valueName": "avg",
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(irate(istio_tcp_sent_bytes_total{reporter=\"$qrep\",source_workload_namespace=~\"$namespace\", source_workload=~\"$workload\"}[1m]))+ sum(irate(istio_tcp_received_bytes_total{reporter=\"$qrep\", source_workload_namespace=~\"$namespace\",source_workload=~\"$workload\"}[1m]))"
      }
     ]
    }
   ]
  },
  {
   "title": "InboundWorkloads",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "type": "text",
     "gridPos": { "h": 3, "w": 24, "x": 0, "y": 13 },
     "options": {
      "content": "<divclass=\"dashboard-header text-center\">\n<span>INBOUND WORKLOADS</span>\n</div>"
     },
     "content": "<divclass=\"dashboard-header text-center\">\n<span>INBOUND WORKLOADS</span>\n</div>"
    },
    {
     "title": "IncomingRequests By Source And Response Code",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 16 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "round(sum(irate(istio_requests_total{connection_security_policy=\"mutual_tls\",destination_workload_namespace=~\"$namespace\", destination_workload=~\"$workload\",reporter=\"$qrep\", source_workload=~\"$srcwl\", source_workload_namespace=~\"$srcns\"}[5m]))by (source_workload, source_workload_namespace, response_code), 0.001)",
       "legendFormat": "{{source_workload }}.{{ source_workload_namespace }} : {{ response_code }} (U0001F510mTLS)"
      },
      {
       "expr": "round(sum(irate(istio_requests_total{connection_security_policy!=\"mutual_tls\",destination_workload_namespace=~\"$namespace\", destination_workload=~\"$workload\",reporter=\"$qrep\", source_workload=~\"$srcwl\", source_workload_namespace=~\"$srcns\"}[5m]))by (source_workload, source_workload_namespace, response_code), 0.001)",
       "legendFormat": "{{source_workload }}.{{ source_workload_namespace }} : {{ response_code }}"
      }
     ]
    },
    {
     "title": "IncomingSuccess Rate (non-5xx responses) By Source",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 16 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "sum(irate(istio_requests_total{reporter=\"$qrep\",connection_security_policy=\"mutual_tls\", destination_workload_namespace=~\"$namespace\",destination_workload=~\"$workload\",response_code!~\"5.*\", source_workload=~\"$srcwl\",source_workload_namespace=~\"$srcns\"}[5m])) by (source_workload, source_workload_namespace)/ sum(irate(istio_requests_total{reporter=\"$qrep\", connection_security_policy=\"mutual_tls\",destination_workload_namespace=~\"$namespace\", destination_workload=~\"$workload\",source_workload=~\"$srcwl\", source_workload_namespace=~\"$srcns\"}[5m]))by (source_workload, source_workload_namespace)",
       "legendFormat": "{{source_workload }}.{{ source_workload_namespace }} (U0001F510mTLS)"
      },
      {
       "expr": "sum(irate(istio_requests_total{reporter=\"$qrep\",connection_security_policy!=\"mutual_tls\", destination_workload_namespace=~\"$namespace\",destination_workload=~\"$workload\",response_code!~\"5.*\", source_workload=~\"$srcwl\",source_workload_namespace=~\"$srcns\"}[5m])) by (source_workload, source_workload_namespace)/ sum(irate(istio_requests_total{reporter=\"$qrep\", connection_security_policy!=\"mutual_tls\",destination_workload_namespace=~\"$namespace\", destination_workload=~\"$workload\",source_workload=~\"$srcwl\", source_workload_namespace=~\"$srcns\"}[5m]))by (source_workload, source_workload_namespace)",
       "legendFormat": "{{source_workload }}.{{ source_workload_namespace }}"
      }
     ]
    },
    {
     "title": "IncomingRequest Duration By Source",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 22 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "(histogram_quantile(0.50,sum(irate(istio_request_duration_milliseconds_bucket{reporter=\"$qrep\", connection_security_policy=\"mutual_tls\",destination_workload=~\"$workload\", destination_workload_namespace=~\"$namespace\",source_workload=~\"$srcwl\", source_workload_namespace=~\"$srcns\"}[1m]))by (source_workload, source_workload_namespace, le)) / 1000) or histogram_quantile(0.50,sum(irate(istio_request_duration_seconds_bucket{reporter=\"$qrep\", connection_security_policy=\"mutual_tls\",destination_workload=~\"$workload\", destination_workload_namespace=~\"$namespace\",source_workload=~\"$srcwl\", source_workload_namespace=~\"$srcns\"}[1m]))by (source_workload, source_workload_namespace, le))",
       "legendFormat": "{{source_workload}}.{{source_workload_namespace}}P50 (U0001F510mTLS)"
      },
      {
       "expr": "(histogram_quantile(0.90,sum(irate(istio_request_duration_milliseconds_bucket{reporter=\"$qrep\", connection_security_policy=\"mutual_tls\",destination_workload=~\"$workload\", destination_workload_namespace=~\"$namespace\",source_workload=~\"$srcwl\", source_workload_namespace=~\"$srcns\"}[1m]))by (source_workload, source_workload_namespace, le)) / 1000) or histogram_quantile(0.90,sum(irate(istio_request_duration_seconds_bucket{reporter=\"$qrep\", connection_security_policy=\"mutual_tls\",destination_workload=~\"$workload\", destination_workload_namespace=~\"$namespace\",source_workload=~\"$srcwl\", source_workload_namespace=~\"$srcns\"}[1m]))by (source_workload, source_workload_namespace, le))",
       "legendFormat": "{{source_workload}}.{{source_workload_namespace}}P90 (U0001F510mTLS)"
      },
      {
       "expr": "(histogram_quantile(0.95,sum(irate(istio_request_duration_milliseconds_bucket{reporter=\"$qrep\", connection_security_policy=\"mutual_tls\",destination_workload=~\"$workload\", destination_workload_namespace=~\"$namespace\",source_workload=~\"$srcwl\", source_workload_namespace=~\"$srcns\"}[1m]))by (source_workload, source_workload_namespace, le)) / 1000) or histogram_quantile(0.95,sum(irate(istio_request_duration_seconds_bucket{reporter=\"$qrep\", connection_security_policy=\"mutual_tls\",destination_workload=~\"$workload\", destination_workload_namespace=~\"$namespace\",source_workload=~\"$srcwl\", source_workload_namespace=~\"$srcns\"}[1m]))by (source_workload, source_workload_namespace, le))",
       "legendFormat": "{{source_workload}}.{{source_workload_namespace}}P95 (U0001F510mTLS)"
      },
      {
       "expr": "(histogram_quantile(0.99,sum(irate(istio_request_duration_milliseconds_bucket{reporter=\"$qrep\", connection_security_policy=\"mutual_tls\",destination_workload=~\"$workload\", destination_workload_namespace=~\"$namespace\",source_workload=~\"$srcwl\", source_workload_namespace=~\"$srcns\"}[1m]))by (source_workload, source_workload_namespace, le)) / 1000) or histogram_quantile(0.99,sum(irate(istio_request_duration_seconds_bucket{reporter=\"$qrep\", connection_security_policy=\"mutual_tls\",destination_workload=~\"$workload\", destination_workload_namespace=~\"$namespace\",source_workload=~\"$srcwl\", source_workload_namespace=~\"$srcns\"}[1m]))by (source_workload, source_workload_namespace, le))",
       "legendFormat": "{{source_workload}}.{{source_workload_namespace}}P99 (U0001F510mTLS)"
      },
      {
       "expr": "(histogram_quantile(0.50,sum(irate(istio_request_duration_milliseconds_bucket{reporter=\"$qrep\", connection_security_policy!=\"mutual_tls\",destination_workload=~\"$workload\", destination_workload_namespace=~\"$namespace\",source_workload=~\"$srcwl\", source_workload_namespace=~\"$srcns\"}[1m]))by (source_workload, source_workload_namespace, le)) / 1000) or histogram_quantile(0.50,sum(irate(istio_request_duration_seconds_bucket{reporter=\"$qrep\", connection_security_policy!=\"mutual_tls\",destination_workload=~\"$workload\", destination_workload_namespace=~\"$namespace\",source_workload=~\"$srcwl\", source_workload_namespace=~\"$srcns\"}[1m]))by (source_workload, source_workload_namespace, le))",
       "legendFormat": "{{source_workload}}.{{source_workload_namespace}}P50"
      },
      {
       "expr": "(histogram_quantile(0.90, sum(irate(istio_request_duration_milliseconds_bucket{reporter=\"$qrep\",connection_security_policy!=\"mutual_tls\", destination_workload=~\"$workload\",destination_workload_namespace=~\"$namespace\", source_workload=~\"$srcwl\",source_workload_namespace=~\"$srcns\"}[1m])) by (source_workload, source_workload_namespace,le)) / 1000) or histogram_quantile(0.90, sum(irate(istio_request_duration_seconds_bucket{reporter=\"$qrep\",connection_security_policy!=\"mutual_tls\", destination_workload=~\"$workload\",destination_workload_namespace=~\"$namespace\", source_workload=~\"$srcwl\",source_workload_namespace=~\"$srcns\"}[1m])) by (source_workload, source_workload_namespace,le))",
       "legendFormat": "{{source_workload}}.{{source_workload_namespace}}P90"
      },
      {
       "expr": "(histogram_quantile(0.95, sum(irate(istio_request_duration_milliseconds_bucket{reporter=\"$qrep\",connection_security_policy!=\"mutual_tls\", destination_workload=~\"$workload\",destination_workload_namespace=~\"$namespace\", source_workload=~\"$srcwl\",source_workload_namespace=~\"$srcns\"}[1m])) by (source_workload, source_workload_namespace,le)) / 1000) or histogram_quantile(0.95, sum(irate(istio_request_duration_seconds_bucket{reporter=\"$qrep\",connection_security_policy!=\"mutual_tls\", destination_workload=~\"$workload\",destination_workload_namespace=~\"$namespace\", source_workload=~\"$srcwl\",source_workload_namespace=~\"$srcns\"}[1m])) by (source_workload, source_workload_namespace,le))",
       "legendFormat": "{{source_workload}}.{{source_workload_namespace}}P95"
      },
      {
       "expr": "(histogram_quantile(0.99, sum(irate(istio_request_duration_milliseconds_bucket{reporter=\"$qrep\",connection_security_policy!=\"mutual_tls\", destination_workload=~\"$workload\",destination_workload_namespace=~\"$namespace\", source_workload=~\"$srcwl\",source_workload_namespace=~\"$srcns\"}[1m])) by (source_workload, source_workload_namespace,le)) / 1000) or histogram_quantile(0.99, sum(irate(istio_request_duration_seconds_bucket{reporter=\"$qrep\",connection_security_policy!=\"mutual_tls\", destination_workload=~\"$workload\",destination_workload_namespace=~\"$namespace\", source_workload=~\"$srcwl\",source_workload_namespace=~\"$srcns\"}[1m])) by (source_workload, source_workload_namespace,le))",
       "legendFormat": "{{source_workload}}.{{source_workload_namespace}}P99"
      }
     ]
    },
    {
     "title": "IncomingRequest Size By Source",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 22 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.50,sum(irate(istio_request_bytes_bucket{reporter=\"$qrep\", connection_security_policy=\"mutual_tls\",destination_workload=~\"$workload\", destination_workload_namespace=~\"$namespace\",source_workload=~\"$srcwl\", source_workload_namespace=~\"$srcns\"}[1m]))by (source_workload, source_workload_namespace, le))",
       "legendFormat": "{{source_workload}}.{{source_workload_namespace}}P50 (U0001F510mTLS)"
      },
      {
       "expr": "histogram_quantile(0.90,sum(irate(istio_request_bytes_bucket{reporter=\"$qrep\", connection_security_policy=\"mutual_tls\",destination_workload=~\"$workload\", destination_workload_namespace=~\"$namespace\",source_workload=~\"$srcwl\", source_workload_namespace=~\"$srcns\"}[1m]))by (source_workload, source_workload_namespace, le))",
       "legendFormat": "{{source_workload}}.{{source_workload_namespace}} P90 (U0001F510mTLS)"
      },
      {
       "expr": "histogram_quantile(0.95,sum(irate(istio_request_bytes_bucket{reporter=\"$qrep\", connection_security_policy=\"mutual_tls\",destination_workload=~\"$workload\", destination_workload_namespace=~\"$namespace\",source_workload=~\"$srcwl\", source_workload_namespace=~\"$srcns\"}[1m]))by (source_workload, source_workload_namespace, le))",
       "legendFormat": "{{source_workload}}.{{source_workload_namespace}}P95 (U0001F510mTLS)"
      },
      {
       "expr": "histogram_quantile(0.99,sum(irate(istio_request_bytes_bucket{reporter=\"$qrep\", connection_security_policy=\"mutual_tls\",destination_workload=~\"$workload\", destination_workload_namespace=~\"$namespace\",source_workload=~\"$srcwl\", source_workload_namespace=~\"$srcns\"}[1m]))by (source_workload, source_workload_namespace, le))",
       "legendFormat": "{{source_workload}}.{{source_workload_namespace}} P99 (U0001F510mTLS)"
      },
      {
       "expr": "histogram_quantile(0.50,sum(irate(istio_request_bytes_bucket{reporter=\"$qrep\", connection_security_policy!=\"mutual_tls\",destination_workload=~\"$workload\", destination_workload_namespace=~\"$namespace\",source_workload=~\"$srcwl\", source_workload_namespace=~\"$srcns\"}[1m]))by (source_workload, source_workload_namespace, le))",
       "legendFormat": "{{source_workload}}.{{source_workload_namespace}}P50"
      },
      {
       "expr": "histogram_quantile(0.90, sum(irate(istio_request_bytes_bucket{reporter=\"$qrep\",connection_security_policy!=\"mutual_tls\", destination_workload=~\"$workload\",destination_workload_namespace=~\"$namespace\", source_workload=~\"$srcwl\",source_workload_namespace=~\"$srcns\"}[1m])) by (source_workload, source_workload_namespace,le))",
       "legendFormat": "{{source_workload}}.{{source_workload_namespace}}P90"
      },
      {
       "expr": "histogram_quantile(0.95, sum(irate(istio_request_bytes_bucket{reporter=\"$qrep\",connection_security_policy!=\"mutual_tls\", destination_workload=~\"$workload\",destination_workload_namespace=~\"$namespace\", source_workload=~\"$srcwl\",source_workload_namespace=~\"$srcns\"}[1m])) by (source_workload, source_workload_namespace,le))",
       "legendFormat": "{{source_workload}}.{{source_workload_namespace}}P95"
      },
      {
       "expr": "histogram_quantile(0.99, sum(irate(istio_request_bytes_bucket{reporter=\"$qrep\",connection_security_policy!=\"mutual_tls\", destination_workload=~\"$workload\",destination_workload_namespace=~\"$namespace\", source_workload=~\"$srcwl\",source_workload_namespace=~\"$srcns\"}[1m])) by (source_workload, source_workload_namespace,le))",
       "legendFormat": "{{source_workload}}.{{source_workload_namespace}}P99"
      }
     ]
    },
    {
     "title": "ResponseSize By Source",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 22 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.50,sum(irate(istio_response_bytes_bucket{reporter=\"$qrep\", connection_security_policy=\"mutual_tls\",destination_workload=~\"$workload\", destination_workload_namespace=~\"$namespace\",source_workload=~\"$srcwl\", source_workload_namespace=~\"$srcns\"}[1m]))by (source_workload, source_workload_namespace, le))",
       "legendFormat": "{{source_workload}}.{{source_workload_namespace}}P50 (U0001F510mTLS)"
      },
      {
       "expr": "histogram_quantile(0.90,sum(irate(istio_response_bytes_bucket{reporter=\"$qrep\", connection_security_policy=\"mutual_tls\",destination_workload=~\"$workload\", destination_workload_namespace=~\"$namespace\",source_workload=~\"$srcwl\", source_workload_namespace=~\"$srcns\"}[1m]))by (source_workload, source_workload_namespace, le))",
       "legendFormat": "{{source_workload}}.{{source_workload_namespace}} P90 (U0001F510mTLS)"
      },
      {
       "expr": "histogram_quantile(0.95,sum(irate(istio_response_bytes_bucket{reporter=\"$qrep\", connection_security_policy=\"mutual_tls\",destination_workload=~\"$workload\", destination_workload_namespace=~\"$namespace\",source_workload=~\"$srcwl\", source_workload_namespace=~\"$srcns\"}[1m]))by (source_workload, source_workload_namespace, le))",
       "legendFormat": "{{source_workload}}.{{source_workload_namespace}}P95 (U0001F510mTLS)"
      },
      {
       "expr": "histogram_quantile(0.99,sum(irate(istio_response_bytes_bucket{reporter=\"$qrep\", connection_security_policy=\"mutual_tls\",destination_workload=~\"$workload\", destination_workload_namespace=~\"$namespace\",source_workload=~\"$srcwl\", source_workload_namespace=~\"$srcns\"}[1m]))by (source_workload, source_workload_namespace, le))",
       "legendFormat": "{{source_workload}}.{{source_workload_namespace}} P99 (U0001F510mTLS)"
      },
      {
       "expr": "histogram_quantile(0.50,sum(irate(istio_response_bytes_bucket{reporter=\"$qrep\", connection_security_policy!=\"mutual_tls\",destination_workload=~\"$workload\", destination_workload_namespace=~\"$namespace\",source_workload=~\"$srcwl\", source_workload_namespace=~\"$srcns\"}[1m]))by (source_workload, source_workload_namespace, le))",
       "legendFormat": "{{source_workload}}.{{source_workload_namespace}}P50"
      },
      {
       "expr": "histogram_quantile(0.90, sum(irate(istio_response_bytes_bucket{reporter=\"$qrep\",connection_security_policy!=\"mutual_tls\", destination_workload=~\"$workload\",destination_workload_namespace=~\"$namespace\", source_workload=~\"$srcwl\",source_workload_namespace=~\"$srcns\"}[1m])) by (source_workload, source_workload_namespace,le))",
       "legendFormat": "{{source_workload}}.{{source_workload_namespace}}P90"
      },
      {
       "expr": "histogram_quantile(0.95, sum(irate(istio_response_bytes_bucket{reporter=\"$qrep\",connection_security_policy!=\"mutual_tls\", destination_workload=~\"$workload\",destination_workload_namespace=~\"$namespace\", source_workload=~\"$srcwl\",source_workload_namespace=~\"$srcns\"}[1m])) by (source_workload, source_workload_namespace,le))",
       "legendFormat": "{{source_workload}}.{{source_workload_namespace}}P95"
      },
      {
       "expr": "histogram_quantile(0.99, sum(irate(istio_response_bytes_bucket{reporter=\"$qrep\",connection_security_policy!=\"mutual_tls\", destination_workload=~\"$workload\",destination_workload_namespace=~\"$namespace\", source_workload=~\"$srcwl\",source_workload_namespace=~\"$srcns\"}[1m])) by (source_workload, source_workload_namespace,le))",
       "legendFormat": "{{source_workload}}.{{source_workload_namespace}}P99"
      }
     ]
    },
    {
     "title": "BytesReceived from Incoming TCP Connection",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 28 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "round(sum(irate(istio_tcp_received_bytes_total{reporter=\"$qrep\",connection_security_policy=\"mutual_tls\", destination_workload_namespace=~\"$namespace\",destination_workload=~\"$workload\", source_workload=~\"$srcwl\", source_workload_namespace=~\"$srcns\"}[1m]))by (source_workload, source_workload_namespace), 0.001)",
       "legendFormat": "{{source_workload }}.{{ source_workload_namespace}} (U0001F510mTLS)"
      },
      {
       "expr": "round(sum(irate(istio_tcp_received_bytes_total{reporter=\"$qrep\",connection_security_policy!=\"mutual_tls\", destination_workload_namespace=~\"$namespace\",destination_workload=~\"$workload\", source_workload=~\"$srcwl\", source_workload_namespace=~\"$srcns\"}[1m]))by (source_workload, source_workload_namespace), 0.001)",
       "legendFormat": "{{source_workload }}.{{ source_workload_namespace}}"
      }
     ]
    },
    {
     "title": "BytesSent to Incoming TCP Connection",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 28 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "round(sum(irate(istio_tcp_sent_bytes_total{connection_security_policy=\"mutual_tls\",reporter=\"$qrep\", destination_workload_namespace=~\"$namespace\", destination_workload=~\"$workload\",source_workload=~\"$srcwl\", source_workload_namespace=~\"$srcns\"}[1m]))by (source_workload, source_workload_namespace), 0.001)",
       "legendFormat": "{{source_workload }}.{{ source_workload_namespace}} (U0001F510mTLS)"
      },
      {
       "expr": "round(sum(irate(istio_tcp_sent_bytes_total{connection_security_policy!=\"mutual_tls\",reporter=\"$qrep\", destination_workload_namespace=~\"$namespace\", destination_workload=~\"$workload\",source_workload=~\"$srcwl\", source_workload_namespace=~\"$srcns\"}[1m]))by (source_workload, source_workload_namespace), 0.001)",
       "legendFormat": "{{source_workload }}.{{ source_workload_namespace}}"
      }
     ]
    }
   ]
  },
  {
   "title": "OutboundServices",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "type": "text",
     "gridPos": { "h": 3, "w": 24, "x": 0, "y": 14 },
     "options": {
      "content": "<divclass=\"dashboard-header text-center\">\n<span>OUTBOUND SERVICES</span>\n</div>"
     },
     "content": "<divclass=\"dashboard-header text-center\">\n<span>OUTBOUND SERVICES</span>\n</div>"
    },
    {
     "title": "OutgoingRequests By Destination And Response Code",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 17 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "round(sum(irate(istio_requests_total{connection_security_policy=\"mutual_tls\",source_workload_namespace=~\"$namespace\", source_workload=~\"$workload\",reporter=\"source\", destination_service=~\"$dstsvc\"}[5m])) by (destination_service,response_code), 0.001)",
       "legendFormat": "{{destination_service }} : {{ response_code }} (U0001F510mTLS)"
      },
      {
       "expr": "round(sum(irate(istio_requests_total{connection_security_policy!=\"mutual_tls\",source_workload_namespace=~\"$namespace\", source_workload=~\"$workload\",reporter=\"source\", destination_service=~\"$dstsvc\"}[5m])) by (destination_service,response_code), 0.001)",
       "legendFormat": "{{destination_service }} : {{ response_code }}"
      }
     ]
    },
    {
     "title": "OutgoingSuccess Rate (non-5xx responses) By Destination",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 17 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "sum(irate(istio_requests_total{reporter=\"source\",connection_security_policy=\"mutual_tls\", source_workload_namespace=~\"$namespace\",source_workload=~\"$workload\",response_code!~\"5.*\", destination_service=~\"$dstsvc\"}[5m]))by (destination_service) / sum(irate(istio_requests_total{reporter=\"source\",connection_security_policy=\"mutual_tls\", source_workload_namespace=~\"$namespace\",source_workload=~\"$workload\", destination_service=~\"$dstsvc\"}[5m]))by (destination_service)",
       "legendFormat": "{{destination_service }} (U0001F510mTLS)"
      },
      {
       "expr": "sum(irate(istio_requests_total{reporter=\"source\",connection_security_policy!=\"mutual_tls\", source_workload_namespace=~\"$namespace\",source_workload=~\"$workload\",response_code!~\"5.*\", destination_service=~\"$dstsvc\"}[5m]))by (destination_service) / sum(irate(istio_requests_total{reporter=\"source\",connection_security_policy!=\"mutual_tls\", source_workload_namespace=~\"$namespace\",source_workload=~\"$workload\", destination_service=~\"$dstsvc\"}[5m]))by (destination_service)",
       "legendFormat": "{{destination_service }}"
      }
     ]
    },
    {
     "title": "OutgoingRequest Duration By Destination",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 23 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "(histogram_quantile(0.50,sum(irate(istio_request_duration_milliseconds_bucket{reporter=\"source\",connection_security_policy=\"mutual_tls\", source_workload=~\"$workload\",source_workload_namespace=~\"$namespace\", destination_service=~\"$dstsvc\"}[1m]))by (destination_service, le)) / 1000) or histogram_quantile(0.50, sum(irate(istio_request_duration_seconds_bucket{reporter=\"source\",connection_security_policy=\"mutual_tls\", source_workload=~\"$workload\",source_workload_namespace=~\"$namespace\", destination_service=~\"$dstsvc\"}[1m]))by (destination_service, le))",
       "legendFormat": "{{destination_service }} P50 (U0001F510mTLS)"
      },
      {
       "expr": "(histogram_quantile(0.90,sum(irate(istio_request_duration_milliseconds_bucket{reporter=\"source\",connection_security_policy=\"mutual_tls\", source_workload=~\"$workload\",source_workload_namespace=~\"$namespace\", destination_service=~\"$dstsvc\"}[1m]))by (destination_service, le)) / 1000) or histogram_quantile(0.90, sum(irate(istio_request_duration_seconds_bucket{reporter=\"source\",connection_security_policy=\"mutual_tls\", source_workload=~\"$workload\",source_workload_namespace=~\"$namespace\", destination_service=~\"$dstsvc\"}[1m]))by (destination_service, le))",
       "legendFormat": "{{destination_service }} P90 (U0001F510mTLS)"
      },
      {
       "expr": "(histogram_quantile(0.95,sum(irate(istio_request_duration_milliseconds_bucket{reporter=\"source\",connection_security_policy=\"mutual_tls\", source_workload=~\"$workload\",source_workload_namespace=~\"$namespace\", destination_service=~\"$dstsvc\"}[1m]))by (destination_service, le)) / 1000) or histogram_quantile(0.95, sum(irate(istio_request_duration_seconds_bucket{reporter=\"source\",connection_security_policy=\"mutual_tls\", source_workload=~\"$workload\",source_workload_namespace=~\"$namespace\", destination_service=~\"$dstsvc\"}[1m]))by (destination_service, le))",
       "legendFormat": "{{destination_service }} P95 (U0001F510mTLS)"
      },
      {
       "expr": "(histogram_quantile(0.99,sum(irate(istio_request_duration_milliseconds_bucket{reporter=\"source\",connection_security_policy=\"mutual_tls\", source_workload=~\"$workload\",source_workload_namespace=~\"$namespace\", destination_service=~\"$dstsvc\"}[1m]))by (destination_service, le)) / 1000) or histogram_quantile(0.99, sum(irate(istio_request_duration_seconds_bucket{reporter=\"source\",connection_security_policy=\"mutual_tls\", source_workload=~\"$workload\",source_workload_namespace=~\"$namespace\", destination_service=~\"$dstsvc\"}[1m]))by (destination_service, le))",
       "legendFormat": "{{destination_service }} P99 (U0001F510mTLS)"
      },
      {
       "expr": "(histogram_quantile(0.50,sum(irate(istio_request_duration_milliseconds_bucket{reporter=\"source\",connection_security_policy!=\"mutual_tls\", source_workload=~\"$workload\",source_workload_namespace=~\"$namespace\", destination_service=~\"$dstsvc\"}[1m]))by (destination_service, le)) / 1000) or histogram_quantile(0.50, sum(irate(istio_request_duration_seconds_bucket{reporter=\"source\",connection_security_policy!=\"mutual_tls\", source_workload=~\"$workload\",source_workload_namespace=~\"$namespace\", destination_service=~\"$dstsvc\"}[1m]))by (destination_service, le))",
       "legendFormat": "{{destination_service }} P50"
      },
      {
       "expr": "(histogram_quantile(0.90,sum(irate(istio_request_duration_milliseconds_bucket{reporter=\"source\",connection_security_policy!=\"mutual_tls\", source_workload=~\"$workload\",source_workload_namespace=~\"$namespace\", destination_service=~\"$dstsvc\"}[1m]))by (destination_service, le)) / 1000) or histogram_quantile(0.90, sum(irate(istio_request_duration_seconds_bucket{reporter=\"source\",connection_security_policy!=\"mutual_tls\", source_workload=~\"$workload\",source_workload_namespace=~\"$namespace\", destination_service=~\"$dstsvc\"}[1m]))by (destination_service, le))",
       "legendFormat": "{{destination_service }} P90"
      },
      {
       "expr": "(histogram_quantile(0.95,sum(irate(istio_request_duration_milliseconds_bucket{reporter=\"source\",connection_security_policy!=\"mutual_tls\", source_workload=~\"$workload\",source_workload_namespace=~\"$namespace\", destination_service=~\"$dstsvc\"}[1m]))by (destination_service, le)) / 1000) or histogram_quantile(0.95, sum(irate(istio_request_duration_seconds_bucket{reporter=\"source\",connection_security_policy!=\"mutual_tls\", source_workload=~\"$workload\",source_workload_namespace=~\"$namespace\", destination_service=~\"$dstsvc\"}[1m]))by (destination_service, le))",
       "legendFormat": "{{destination_service }} P95"
      },
      {
       "expr": "(histogram_quantile(0.99,sum(irate(istio_request_duration_milliseconds_bucket{reporter=\"source\",connection_security_policy!=\"mutual_tls\", source_workload=~\"$workload\",source_workload_namespace=~\"$namespace\", destination_service=~\"$dstsvc\"}[1m]))by (destination_service, le)) / 1000) or histogram_quantile(0.99, sum(irate(istio_request_duration_seconds_bucket{reporter=\"source\",connection_security_policy!=\"mutual_tls\", source_workload=~\"$workload\",source_workload_namespace=~\"$namespace\", destination_service=~\"$dstsvc\"}[1m]))by (destination_service, le))",
       "legendFormat": "{{destination_service }} P99"
      }
     ]
    },
    {
     "title": "OutgoingRequest Size By Destination",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 23 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.50,sum(irate(istio_request_bytes_bucket{reporter=\"source\", connection_security_policy=\"mutual_tls\",source_workload=~\"$workload\", source_workload_namespace=~\"$namespace\",destination_service=~\"$dstsvc\"}[1m])) by (destination_service, le))",
       "legendFormat": "{{destination_service }} P50 (U0001F510mTLS)"
      },
      {
       "expr": "histogram_quantile(0.90,sum(irate(istio_request_bytes_bucket{reporter=\"source\", connection_security_policy=\"mutual_tls\",source_workload=~\"$workload\", source_workload_namespace=~\"$namespace\",destination_service=~\"$dstsvc\"}[1m])) by (destination_service, le))",
       "legendFormat": "{{destination_service }} P90 (U0001F510mTLS)"
      },
      {
       "expr": "histogram_quantile(0.95,sum(irate(istio_request_bytes_bucket{reporter=\"source\", connection_security_policy=\"mutual_tls\",source_workload=~\"$workload\", source_workload_namespace=~\"$namespace\",destination_service=~\"$dstsvc\"}[1m])) by (destination_service, le))",
       "legendFormat": "{{destination_service }} P95 (U0001F510mTLS)"
      },
      {
       "expr": "histogram_quantile(0.99,sum(irate(istio_request_bytes_bucket{reporter=\"source\", connection_security_policy=\"mutual_tls\",source_workload=~\"$workload\", source_workload_namespace=~\"$namespace\",destination_service=~\"$dstsvc\"}[1m])) by (destination_service, le))",
       "legendFormat": "{{destination_service }} P99 (U0001F510mTLS)"
      },
      {
       "expr": "histogram_quantile(0.50,sum(irate(istio_request_bytes_bucket{reporter=\"source\", connection_security_policy!=\"mutual_tls\",source_workload=~\"$workload\", source_workload_namespace=~\"$namespace\",destination_service=~\"$dstsvc\"}[1m])) by (destination_service, le))",
       "legendFormat": "{{destination_service }} P50"
      },
      {
       "expr": "histogram_quantile(0.90,sum(irate(istio_request_bytes_bucket{reporter=\"source\", connection_security_policy!=\"mutual_tls\",source_workload=~\"$workload\", source_workload_namespace=~\"$namespace\",destination_service=~\"$dstsvc\"}[1m])) by (destination_service, le))",
       "legendFormat": "{{destination_service }} P90"
      },
      {
       "expr": "histogram_quantile(0.95,sum(irate(istio_request_bytes_bucket{reporter=\"source\", connection_security_policy!=\"mutual_tls\",source_workload=~\"$workload\", source_workload_namespace=~\"$namespace\",destination_service=~\"$dstsvc\"}[1m])) by (destination_service, le))",
       "legendFormat": "{{destination_service }} P95"
      },
      {
       "expr": "histogram_quantile(0.99,sum(irate(istio_request_bytes_bucket{reporter=\"source\", connection_security_policy!=\"mutual_tls\",source_workload=~\"$workload\", source_workload_namespace=~\"$namespace\",destination_service=~\"$dstsvc\"}[1m])) by (destination_service, le))",
       "legendFormat": "{{destination_service }} P99"
      }
     ]
    },
    {
     "title": "ResponseSize By Destination",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 23 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.50,sum(irate(istio_response_bytes_bucket{reporter=\"source\", connection_security_policy=\"mutual_tls\",source_workload=~\"$workload\", source_workload_namespace=~\"$namespace\",destination_service=~\"$dstsvc\"}[1m])) by (destination_service, le))",
       "legendFormat": "{{destination_service }} P50 (U0001F510mTLS)"
      },
      {
       "expr": "histogram_quantile(0.90,sum(irate(istio_response_bytes_bucket{reporter=\"source\", connection_security_policy=\"mutual_tls\",source_workload=~\"$workload\", source_workload_namespace=~\"$namespace\",destination_service=~\"$dstsvc\"}[1m])) by (destination_service, le))",
       "legendFormat": "{{destination_service }} P90 (U0001F510mTLS)"
      },
      {
       "expr": "histogram_quantile(0.95,sum(irate(istio_response_bytes_bucket{reporter=\"source\", connection_security_policy=\"mutual_tls\",source_workload=~\"$workload\", source_workload_namespace=~\"$namespace\",destination_service=~\"$dstsvc\"}[1m])) by (destination_service, le))",
       "legendFormat": "{{destination_service }} P95 (U0001F510mTLS)"
      },
      {
       "expr": "histogram_quantile(0.99,sum(irate(istio_response_bytes_bucket{reporter=\"source\", connection_security_policy=\"mutual_tls\",source_workload=~\"$workload\", source_workload_namespace=~\"$namespace\",destination_service=~\"$dstsvc\"}[1m])) by (destination_service, le))",
       "legendFormat": "{{destination_service }}  P99 (U0001F510mTLS)"
      },
      {
       "expr": "histogram_quantile(0.50,sum(irate(istio_response_bytes_bucket{reporter=\"source\", connection_security_policy!=\"mutual_tls\",source_workload=~\"$workload\", source_workload_namespace=~\"$namespace\",destination_service=~\"$dstsvc\"}[1m])) by (destination_service, le))",
       "legendFormat": "{{destination_service }} P50"
      },
      {
       "expr": "histogram_quantile(0.90,sum(irate(istio_response_bytes_bucket{reporter=\"source\", connection_security_policy!=\"mutual_tls\",source_workload=~\"$workload\", source_workload_namespace=~\"$namespace\",destination_service=~\"$dstsvc\"}[1m])) by (destination_service, le))",
       "legendFormat": "{{destination_service }} P90"
      },
      {
       "expr": "histogram_quantile(0.95,sum(irate(istio_response_bytes_bucket{reporter=\"source\", connection_security_policy!=\"mutual_tls\",source_workload=~\"$workload\", source_workload_namespace=~\"$namespace\",destination_service=~\"$dstsvc\"}[1m])) by (destination_service, le))",
       "legendFormat": "{{destination_service }} P95"
      },
      {
       "expr": "histogram_quantile(0.99,sum(irate(istio_response_bytes_bucket{reporter=\"source\", connection_security_policy!=\"mutual_tls\",source_workload=~\"$workload\", source_workload_namespace=~\"$namespace\",destination_service=~\"$dstsvc\"}[1m])) by (destination_service, le))",
       "legendFormat": "{{destination_service }} P99"
      }
     ]
    },
    {
     "title": "BytesSent on Outgoing TCP Connection",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 29 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "round(sum(irate(istio_tcp_sent_bytes_total{connection_security_policy=\"mutual_tls\",reporter=\"source\", source_workload_namespace=~\"$namespace\", source_workload=~\"$workload\",destination_service=~\"$dstsvc\"}[1m])) by (destination_service), 0.001)",
       "legendFormat": "{{destination_service }} (U0001F510mTLS)"
      },
      {
       "expr": "round(sum(irate(istio_tcp_sent_bytes_total{connection_security_policy!=\"mutual_tls\",reporter=\"source\", source_workload_namespace=~\"$namespace\", source_workload=~\"$workload\",destination_service=~\"$dstsvc\"}[1m])) by (destination_service), 0.001)",
       "legendFormat": "{{destination_service }}"
      }
     ]
    },
    {
     "title": "BytesReceived from Outgoing TCP Connection",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 29 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "round(sum(irate(istio_tcp_received_bytes_total{reporter=\"source\",connection_security_policy=\"mutual_tls\", source_workload_namespace=~\"$namespace\",source_workload=~\"$workload\", destination_service=~\"$dstsvc\"}[1m]))by (destination_service), 0.001)",
       "legendFormat": "{{destination_service }} (U0001F510mTLS)"
      },
      {
       "expr": "round(sum(irate(istio_tcp_received_bytes_total{reporter=\"source\",connection_security_policy!=\"mutual_tls\", source_workload_namespace=~\"$namespace\",source_workload=~\"$workload\", destination_service=~\"$dstsvc\"}[1m]))by (destination_service), 0.001)",
       "legendFormat": "{{destination_service }}"
      }
     ]
    }
   ]
  }
 ]
}