---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ .Values.app.name }}
  namespace: {{ .Values.app.namespace }}
spec:
  gateways:
  - {{ .Values.app.name }}
  hosts:
  - {{ .Values.app.istio.host }}
  http:
  - route:
    - destination:
        host: {{ .Values.app.name }}
        port:
          number: {{ .Values.app.port.port }}
    retries:
      attempts: {{ .Values.app.istio.virtualService.http.retries.attempts }}
      perTryTimeout: {{ .Values.app.istio.virtualService.http.retries.perTryTimeout }}
      retryOn: {{ .Values.app.istio.virtualService.http.retries.retryOn }}
---